# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:dubnium-browsers
  working_directory: ~/workspace

jobs:
  audit:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/workspace
      - run: npm audit

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: npm run build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    <<: *defaults

    steps:
      - run: echo 'Deploying ...'
      - run: echo 'Deploying done.'

  e2e:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/workspace
      - run: npm run e2e

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/workspace
      - run: npm run lint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/workspace
      - run: npm test -- --code-coverage --watch=false
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage/report

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - audit:
          requires:
            - build
      - e2e:
          requires:
            - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
            - lint
            - e2e
            - audit
